### ISSUE TITLE
Failing to export data from Cosmos TablesDB

### ISSUE THREAD

**Issue by CodyBatt** [AzureCosmosDB/data-migration-desktop-tool#145]
I'm trying to copy data from one cosmos tablesdb to another. I've also tried exporting to JSON file with the same result:

```
fail: Cosmos.DataTransfer.Core.RunCommand.CommandHandler[0]
      Data transfer failed
      Azure.RequestFailedException: One of the input values is invalid.
      ActivityId: 9ffff170-57e7-4992-8239-233fd54fd54a, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.20348.0
RequestID:9ffff170-57e7-4992-8239-233fd54fd54a

      Status: 400 (Bad Request)
      ErrorCode: InvalidInput

      Content:
      {"odata.error":{"code":"InvalidInput","message":{"lang":"en-us","value":"One of the input values is invalid.\r\nActivityId: 9ffff170-57e7-4992-8239-233fd54fd54a, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.20348.0\nRequestID:9ffff170-57e7-4992-8239-233fd54fd54a\n"}}}


      Headers:
      Date: Tue, 24 Sep 2024 21:54:33 GMT
      Transfer-Encoding: chunked
      Content-Type: application/json;odata=minimalmetadata

         at Azure.Data.Tables.TableRestClient.QueryEntitiesAsync(String table, Nullable`1 timeout, String nextPartitionKey, String nextRowKey, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableClient.<>c__DisplayClass50_0`1.<<QueryAsync>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
         at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
         at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
         at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Cosmos.DataTransfer.AzureTableAPIExtension.AzureTableAPIDataSourceExtension.ReadAsync(IConfiguration config, ILogger logger, CancellationToken cancellationToken)+MoveNext() in /__w/data-migration-desktop-tool/data-migration-desktop-tool/Extensions/AzureTableAPI/Cosmos.DataTransfer.AzureTableAPIExtension/AzureTableAPIDataSourceExtension.cs:line 35
         at Cosmos.DataTransfer.AzureTableAPIExtension.AzureTableAPIDataSourceExtension.ReadAsync(IConfiguration config, ILogger logger, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Cosmos.DataTransfer.AzureTableAPIExtension.AzureTableAPIDataSinkExtension.WriteAsync(IAsyncEnumerable`1 dataItems, IConfiguration config, IDataSourceExtension dataSource, ILogger logger, CancellationToken cancellationToken) in /__w/data-migration-desktop-tool/data-migration-desktop-tool/Extensions/AzureTableAPI/Cosmos.DataTransfer.AzureTableAPIExtension/AzureTableAPIDataSinkExtension.cs:line 27
         at Cosmos.DataTransfer.AzureTableAPIExtension.AzureTableAPIDataSinkExtension.WriteAsync(IAsyncEnumerable`1 dataItems, IConfiguration config, IDataSourceExtension dataSource, ILogger logger, CancellationToken cancellationToken) in /__w/data-migration-desktop-tool/data-migration-desktop-tool/Extensions/AzureTableAPI/Cosmos.DataTransfer.AzureTableAPIExtension/AzureTableAPIDataSinkExtension.cs:line 27
         at Cosmos.DataTransfer.Core.RunCommand.CommandHandler.ExecuteDataTransferOperation(IDataSourceExtension source, IConfiguration sourceConfig, IDataSinkExtension sink, IConfiguration sinkConfig, CancellationToken cancellationToken) in /__w/data-migration-desktop-tool/data-migration-desktop-tool/Core/Cosmos.DataTransfer.Core/RunCommand.cs:line 179
```
Is there any way to get additional information on what might be wrong? `One of the input values is invalid.` isn't very helpful to me.

I get the same error with the old dt.exe after exporting about 34k rows.

I wrote code to do this manually with Azure.Data.Tables API  and I get the same error when fetching the 34th thousand results. In fiddler this is the request (url decoded) that produces a 400 error:

```
https://onepam-dev-vs.table.cosmos.azure.com/credentials()?$format=application/json;odata=minimalmetadata&$top=1000&NextPartitionKey=[{"token":"f2pMAPpsz3v91AAAAAAAAA==","range":{"min":"","max":"FF"}}]&NextRowKey=NA
```

The previous page was returned successfully by this request:
```
https://onepam-dev-vs.table.cosmos.azure.com/credentials()?$format=application/json;odata=minimalmetadata&$top=1000&NextPartitionKey=[{"token":"f2pMAPpsz3vezgAAAAAAAA==","range":{"min":"","max":"FF"}}]&NextRowKey=NA
```

My guess is that the continuation token is invalid for the final page which isn't great for trying to migrate this table. I don't suppose this is a problem with your code. Seems like it's Azure.Data.Tables.

**Comment by CodyBatt** [comment]
Something was wrong with my dev source table. I still don't know what, but it worked for the tables that I needed.
