### ISSUE TITLE
Issues Migration Hierarchically partitioned containers | Multiple Partitions Keys\paths

### ISSUE THREAD

**Issue by omogrosso** [AzureCosmosDB/data-migration-desktop-tool#86]
Dear All,

I've been using the DMT tool several times for migrating containers and seeking data for no-sql cosmos db containers with just one partition key and it works fine but right now I'm trying to migrate a container that has a Hierarchically partitioned containers schema and there is not the way to do it via DMT, at least from my knowledge perspective. 

Does anyone know if is there a way to do this? or is it an unsupported feature? . Just to give you an example what i'm trying to achieve, see the following code:

```
{
    "Source": "json",
    "Sink": "cosmos-nosql",
	"SourceSettings": {
		"FilePath": "https://mytestfiles.local/sales-data.json"
	},
	"SinkSettings": {
		"ConnectionString": "AccountEndpoint=https://...",
		"Database": "myDb",
		"Container": "myContainer",
                 "PartitionKeyPath": ["partitionKey", "categoryCode", "subCategoryCode"],
		"RecreateContainer": true,
		"WriteMode": "Insert",
		"CreatedContainerMaxThroughput": 5000,
		"IsServerlessAccount": false
	}
}
```
I'll really appreciate your guidance, thanks a lot.

Regards

**Comment by bowencode** [comment]
Yes, this is supported for Cosmos-NoSql Sink. From [docs for the Cosmos extension](https://github.com/AzureCosmosDB/data-migration-desktop-tool/blob/main/Extensions/Cosmos/README.md):

> Sink requires an additional PartitionKeyPath parameter which is used when creating the container if it does not exist. To use hierarchical partition keys, instead use the PartitionKeyPaths setting to supply an array of up to 3 paths.

**Comment by omogrosso** [comment]
Thanks a lot for your reply @bowencode  I really appreciate it.

Is there any example you can provide me? I tried but it's complaining about the PartitionKeyPath parameter. This is what I tried:


```
{
  "Source": "json",
  "Sink": "cosmos-nosql",
"SourceSettings": {
  "FilePath": "C:\\Users\\myuser\\Desktop\\myfile\\file.json"
},
"SinkSettings": {
  "ConnectionString": "PLACE_HOLDER_CONNECTION_STRING",
  "Database": "mycosmosdbdatabase",
  "Container": "mycontainer",
  "PartitionKeyPaths ": ["partitionKey","categoryCode","subCategoryCode"],
  "WriteMode": "Insert",
  "CreatedContainerMaxThroughput": 4000,
  "IsServerlessAccount": false
}
}
```
The error I'm receiving is this one: 

```
Using Cosmos-nosql Sink
fail: Cosmos.DataTransfer.Core.RunCommand.CommandHandler[0]
      Data transfer failed
      System.ArgumentNullException: Value cannot be null. (Parameter 'PartitionKeyPath')
         at Microsoft.Azure.Cosmos.ContainerProperties.set_PartitionKeyPath(String value)
         at Cosmos.DataTransfer.CosmosExtension.CosmosDataSinkExtension.WriteAsync(IAsyncEnumerable`1 dataItems, IConfiguration config, IDataSourceExtension dataSource, ILogger logger, CancellationToken cancellationToken) in /__w/data-migration-desktop-tool/data-migration-desktop-tool/Extensions/Cosmos/Cosmos.DataTransfer.CosmosExtension/CosmosDataSinkExtension.cs:line 
59
         at Cosmos.DataTransfer.Core.RunCommand.CommandHandler.ExecuteDataTransferOperation(IDataSourceExtension source, IConfiguration sourceConfig, IDataSinkExtension sink, IConfiguration sinkConfig, CancellationToken cancellationToken) in /__w/data-migration-desktop-tool/data-migration-desktop-tool/Core/Cosmos.DataTransfer.Core/RunCommand.cs:line 179
```
Thanks in advance and my apologies.

Regards

**Comment by omogrosso** [comment]
The issue has been addressed, effectively,it's allowed to restore data with the dmt software when we are using hierarchical partition keys, Here is an example you may use:


```

{
  "Source": "json",
  "Sink": "cosmos-nosql",
"SourceSettings": {
  "FilePath": "REPLACE_YOUR_FILE_PATH>"
},
"SinkSettings": {
  "ConnectionString": "<Replace_with_your_connection_string>",
  "Database": "<YOUR_COSMOS_DB>",
  "Container": "<YOUR_COSMOS_CONTAINER>",
  "PartitionKeyPaths": ["/partition1","/partition2","/partition3"],
  "WriteMode": "Insert",
  "CreatedContainerMaxThroughput": 4000,
  "IsServerlessAccount": false
}
}
```
